# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='id',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paciente_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='profesional_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
