# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160510_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialclinico',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='control',
            name='historial',
        ),
        migrations.RemoveField(
            model_name='control',
            name='profesional_id',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='comuna_id',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='historial',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='persona_apellidomaterno',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='persona_apellidopaterno',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='persona_correo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='persona_direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='persona_fechanacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='persona_nombre',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='persona_rut',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='persona_sexo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='persona_telefonocontacto',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='comuna_id',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='persona_apellidomaterno',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='persona_apellidopaterno',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='persona_correo',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='persona_direccion',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='persona_fechanacimiento',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='persona_nombre',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='persona_rut',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='persona_sexo',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='persona_telefonocontacto',
        ),
        migrations.AddField(
            model_name='control',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='paciente_anamnesis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Historialclinico',
        ),
    ]
