# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_paciente_comuna_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='comuna_id',
        ),
    ]
