# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 01:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('polls', '0005_remove_paciente_comuna_id'),
	]

	operations = [
		migrations.AddField(
			model_name='persona',
			name='user',
			field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
			preserve_default=False,
		),
	]
